version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
  file:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: myapp.log
loggers:
  extract:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no

root:
  level: WARNING
  handlers: [ console ]